services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nutritrack
      POSTGRES_PASSWORD: nutritrack
      POSTGRES_DB: nutritrack
    ports:
      - "5432:5432"
    volumes:
      - nutritrack_pg:/var/lib/postgresql/data
volumes:
  nutritrack_pg:
